theme: jekyll-theme-minimal
logo: '/assets/logo.svg'
title: Supplementary Information -- Hobbs et al., 2023, Evaluation of CAZyme Classifiers
description: Supplementary inforamtion, scripts and data files presented in the manuscript Hobbs et al.
